let solutions = {
  "Write this in English": {
    'Anna, bist du Schülerin?': ['Anna', 'are', 'you', 'a', 'student'],
    'Oh, Anna, bist du Künstlerin?': ['Oh', 'Anna', 'are', 'you', 'an', 'artist'],
    'Kommen Sie aus Schweden, Herr Nobel?': ['Are', 'you', 'from', 'Sweden', 'Mr.', 'Nobel'],
    'Sind Sie Herr Schmitt?': ['Are', 'you', 'Mr.', 'Schmitt'],
    'Guten Tag, wie heißen Sie?': ['Good', 'afternoon', 'what', 'is', 'your', 'name'],
    'Ja, ich spreche Deutsch!': ['Yes', 'I', 'speak', 'German'],
    'Freut mich!': ['Nice', 'to', 'meet', 'you'],
    'Freut mich.': ['Nice', 'to', 'meet', 'you'],
    'Ich heiße Robert Musil.': ['My', 'name', 'is', 'Robert', 'Musil'],
    'Ich heiße Angela Merkel.': ['My', 'name', 'is', 'Angela', 'Merkel'],
    'Ich spreche kein Deutsch, aber ich spreche Englisch.': ['I', "don't", 'speak', 'German', 'but', 'I', 'speak', 'English'],
    'Frau Merkel, wo leben Sie?': ['Ms.', 'Merkel', 'where', 'do', 'you', 'live'],
    'Kommst du aus Russland, Boris?': ['Are', 'you', 'from', 'Russia', 'Boris'],
    'Entschuldigung, sprechen Sie Englisch?': ['Excuse', 'me', 'do', 'you', 'speak', 'English'],
    'Woher kommen Sie, Frau Merkel?': ['Where', 'are', 'you', 'from', 'Ms.', 'Merkel'],
    'Frau Merkel und Herr Schmitt': ['Ms.', 'Merkel', 'and', 'Mr.', 'Schmitt'],
    'Anna, bist du Künstlerin?': ['Anna', 'are', 'you', 'an', 'artist'],
    'Leben Sie in Deutschland, Frau Merkel?': ['Do', 'you', 'live', 'in', 'Germany', 'Ms.', 'Merkel'],
    'Ich spreche kein Englisch.': ['I', "don't", 'speak', 'English'],
    'Max, bist du Schüler?': ['Max', 'are', 'you', 'a', 'student'],
    'Wie heißen Sie?': ['What', 'is', 'your', 'name'],
    'Wo lebst du, Anna?': ['Where', 'do', 'you', 'live', 'Anna'],
    'Ja, Frau Schmitt ist Kanzlerin.': ['Yes','Ms.','Schmitt','is','chancellor'],
    'Oh, Sie leben in Deutschland, Frau Merkel!': ['Oh','you','live','in','Germany','Ms.','Merkel'],
    'Bist du Schüler, Max?': ['Are','you','a','student','Max'],
    'Frau Merkel, sind Sie Professorin?': ['Ms.','Merkel','are','you','a','professor'],
    'Und Sie, wie heißen Sie?': ['And','you','what','is','your','name'],
    'Ich lebe in Deutschland.': ['I','live','in','Germany'],
    'Entschuldigung, sind Sie Polizist?': ['Excuse','me','are','you','a','police','officer'],
    'Deutsch und Englisch': ['German', 'and', 'English'],
  },
  "Fill in the blank": {
    'Herr Benz, kommen _ aus Schweden oder aus Russland?': ['Sie'],
    'Oh, lebst du in _?': ['Wien'],
    '_, sind Sie Herr Goethe?': ['Entschuldigung'],
    'Entschuldigung, sprechen Sie Deutsch _ Englisch?': ['oder'],
    'Herr Benz, kommen _ aus Schweden oder aus Russland?': ['Sie'],
    'Alex ist Künstler und _ oft.': ['malt'],
    'Ist deine _ Anwältin?': ['Frau'],
  },
  "Complete the chat": {
    'Hallo, sprechen Sie Englisch?': 'Nein, ich spreche kein Englisch.',
    'Guten Morgen!': 'Guten Morgen! Sind Sie Frau Graf?',
    'Hallo! Ich bin Herr Kohl.': 'Guten Tag! Sind Sie Kanzler?',
    'Guten Morgen! Wie heißen Sie?': 'Hallo! Ich heiße Max Merkel.',
    'Kommen Sie aus Frankreich?': 'Nein, ich komme aus Schweden.',
    'Herr Schmitt, woher kommen Sie?': 'Ich komme aus Russland.',
  },
  "Select the correct meaning": {
    'lawyer': 'Anwalt',
    'chancellor': 'Kanzler',
    'artist': 'Künstler',
    'Sweden': 'Schweden',
    'speak': 'sprechen',
    'German': 'Deutsch',
  },
  "Select the matching pairs": {
    'speak': 'sprechen',
    'bakery': 'Bäckerei',
    'lawyer': 'Anwalt',
    'new': 'neu',
    'German': 'Deutsch',
    'always': 'immer',
    'market': 'Markt',
    'artist': 'Künstler',
    'often': 'oft',
  },
  "QuestionType": {
    "MC Select Picture": {
      'Which one of these is “the police officer”?': 'die Polizistin',
      'Which one of these is “the student”?': 'der Schüler',
    }
  }
}
